# Generated by Django 2.2.6 on 2019-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test product. This is a quality product. This is a good product.'),
            preserve_default=False,
        ),
    ]
