# Generated by Django 2.2.6 on 2019-12-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
