# Generated by Django 2.2.6 on 2019-12-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20191210_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_info',
        ),
    ]
