# Generated by Django 2.2.6 on 2019-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_item_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
