# Generated by Django 2.2.6 on 2019-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
