# Generated by Django 2.2.6 on 2019-12-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20191216_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='label',
            new_name='colortag',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='discount_cost',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='photo',
        ),
    ]
