# Generated by Django 2.2.6 on 2019-12-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20191219_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='order_begin_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='order_placed_date',
        ),
    ]
